CREATE TABLE carts (

   id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   user_id BIGINT UNSIGNED NOT NULL,
   product_id BIGINT UNSIGNED NOT NULL,
   quantity INT UNSIGNED NOT NULL,
   subtotal DECIMAL(10,2) NOT NULL,
   created_at DATETIME,
   updated_at DATETIME,

   FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
   FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE

);